export const maths = [
  `Matrices`,
  `Determinants`,
  `Relations and Functions`,
  `Inverse Trigonometric Functions`,
  `Continuity and Differentiability`,
  `Application of Derivatives`,
  `Integrals`,
  `Application of Integrals`,
  `Differential Equations`,
  `Vector Algebra`,
  `Three dimensional Geometry`,
  `Linear Programming`,
  `Probability`,
  `Sets`,
  `Trigonometric Functons`,
  `Principle of Mathematical Induction`,
  `Complex Numbers and Quadratic Equations`,
  `Linear Inequalities`,
  `Permutations and Combinations`,
  `Binomial Theorem`,
  `Sequences and Series`,
  `Straight Lines`,
  `Conic Sections`,
  `Introduction to Three Dimensional Geometry`,
  `Limits and Derivatives`,
  `Mathematical Reasoning`,
  `Statistics`,
];

export const physics = [
  `ELECTRIC CHARGES AND FIELDS`,
  `ELECTROSTATIC POTENTIAL AND CAPACITANCE`,
  `CURRENT ELECTRICITY`,
  `MOVING CHARGES AND MAGNETISM`,
  `MAGNETISM AND MATTER`,
  `ELECTROMAGNETIC INDUCTION`,
  `ALTERNATING CURRENT`,
  `ELECTROMAGNETIC WAVES`,
  `RAY OPTICS AND OPTICAL INSTRUMENTS`,
  `WAVE OPTICS`,
  `DUAL NATURE OF RADIATION AND MATTER`,
  `ATOMS`,
  `NUCLEI`,
  `SEMICONDUCTOR ELECTRONICS: MATERIALS, DEVICES AND SIMPLE CIRCUITS`,
  `COMMUNICATION SYSTEMS`,
  `Physical World`,
  `Units and Measurements`,
  `Motion in a Straight Line`,
  `Motion in a Plane`,
  `Laws of Motion`,
  `Work, Energy and Power`,
  `System of Particles and Rotational Motion`,
  `Gravitation`,
  `Mechanical Properties of Solids`,
  `Mechanical Properties of Fluids`,
  `Thermal Properties of Matter`,
  `Thermodynamics`,
  `Kinetic Theory`,
  `Oscillations`,
  `Waves`,
];

export const chemistry = [
  `Some Basic Concepts of Chemistry`,
  `Structure of Atom`,
  `Classification of Elements and Periodicity in properties`,
  `Chemical Bonding and Molecular Structure`,
  `States of Matter`,
  `Thermodynamics`,
  `Equilibrium`,
  `Redox Reactions`,
  `Hydrogen`,
  `The s-Block Elements`,
  `The p-Block Elements`,
  `Organic Chemistry - Some Basic Principles and Techniques`,
  `Hydrocarbons`,
  `Environmental Chemistry`,
  `The Solid State`,
  `Solutions`,
  `Electrochemistry`,
  `Chemical Kinetics`,
  `Surface Chemistry`,
  `General Principles and Processes of Isolation of Elements:`,
  `The P- Block element`,
  `The d and f- block elements`,
  `Coordination Compound`,
  `Haloalkanes and Haloarenes`,
  `Alcohol,Phenols and Ethers`,
  `Aldehydes, Ketones and Carboxylic Acids`,
  `Amines`,
  `Biomolecules`,
  `Polymers`,
  `Chemistry in everyday life`,
];