import {Dimensions, StyleSheet} from 'react-native';

const screen = Dimensions.get('window'),
  vh = screen.height / 100,
  vw = screen.width / 100;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    width: 100 * vw,
    height: 100 * vh,
    paddingTop: 12.5 * vh,
    alignItems: 'center',
  },
   containerVideo: {
    flex: 1,
    width: 100 * vw,
    height: 100 * vh,
    paddingTop: 12.5 * vh,
    alignItems: 'center',
  },
  flashCard: {
    height: 27.5 * vh,
    width: 90 * vw,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    shadowOffset: {width: 2, height: 2},
    shadowOpacity: 0.5,
    shadowRadius: 2,
    overflow: 'hidden',
    elevation: 5,

  },
  card: {
    backgroundColor: 'white',
    height: 27.5 * vh,
    width: 90 * vw,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 10,
  },
  courseList: {
    // height: 35*vh,
    width: 90 * vw,
    alignItems: 'center',
     marginLeft: 3.6 * vw,
    marginTop: '2.5%',

  },
  cardHeader: {
    height: 5 * vh,
    width: '100%',
    flexDirection: 'row',
    paddingLeft: '5%',
  },
  cardTitle: {
    fontSize: 4.5 * vw,
    color: 'black',
  },
  cardShowAll: {
    fontSize: 4.5 * vw,
    position: 'absolute',
    right: 10 * vw,
    color: 'black',
  },
   pageTitle: {
    fontSize: 3.5 * vh,
    color: '#333',
    marginTop: 2.5 * vh,
    textAlign: 'center',
    elevation: 3,
    position: 'absolute',
    fontFamily: 'Montserrat-Medium',
  },
  rightArrowIcon: {
    height: 5 * vw,
    width: 5 * vw,
    position: 'absolute',
    right: 4 * vw,
    marginTop: 0.75 * vw,
  },
  rightArrowIconImage: {
    height: '100%',
    width: '100%',
  },
  listWrapper: {
    // height: 30*vh,
    width: '100%',
  },
  listItem: {
    height: 14 * vh,
    width: '100%',
    marginBottom: '2.5%',
    borderRadius: 10,
    alignItems: 'center',
    elevation: 3,
    flexDirection: 'row',
    backgroundColor: 'white',
  },
  listItem2: {
    height: 14 * vh,
    width: 90 * vw,
    borderRadius: 10,
    marginLeft: 5 * vw,
    marginBottom: '2.5%',
    overflow: 'hidden',
    elevation: 3,
    flexDirection: 'row',
    backgroundColor: 'white',
  },
  courseListIcon: {
    height: 10 * vh,
    width: 10 * vh,
    marginLeft: 2 * vw,
    marginRight: 2 * vw,
  },
  courseListTextContainer: {
    height: '100%',
    flex: 1,
  },
  courseListItemHeading: {
    fontSize: 4.5 * vw,
    marginTop: 3 * vh,
    marginBottom: 0.25 * vh,
    color: 'black',
  },
  courseListItemTeacherName: {
    fontSize: 3.5 * vw,
    opacity: 0.5,
    color: 'black',
  },
  percentComplete: {
    width: 25 * vw,
    justifyContent: 'center',
    alignItems: 'center',
    borderLeftWidth: 1,
    borderLeftColor: 'rgba(0,0,0,0.1)',
    height: '100%',
  },
  percentDataContainer: {
    flexDirection: 'row',
  },
  percent: {
    fontSize: 7.5 * vw,
    color: 'black',
  },
  percentIcon: {
    fontSize: 4 * vw,
    marginTop: vw,
  },
  completedText: {
    fontSize: 3 * vw,
  },
  progressBar: {
    width: 20 * vw,
    height: 0.3 * vh,
    marginTop: vh,
    backgroundColor: '#fafafa',
    opacity: 0.5,
  },
  sectionTitle: {
    fontSize: 7 * vw,
    color: 'white',
    marginTop: 2.25 * vh,
    textAlign: 'center',
  },
  sectionTitleCompleted: {
    fontSize: 6 * vw,
    color: 'white',
    marginTop: 2.5 * vh,
  },
  sectionTitleCompleted1: {
    fontSize: 4.5 * vw,
    color: 'black',
    marginTop: 1.5 * vh,
    marginBottom: 1.5 * vh,
    //fontWeight: 'bold',
    marginLeft: 5 * vw,

  },
  topHeader: {
    height: 18 * vh,
    width: 100 * vw,
    flexDirection: 'row',
    marginTop: vh,
  },
  completedTopHeader: {
    height: 25 * vh,
    width: 100 * vw,
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: vh,
  },
  headerLeftSection: {
    height: '100%',
    width: 66 * vw,
  },
  pointsContainer: {
    backgroundColor: '#5e4096',
    height: 38 * vw,
    width: 38 * vw,
    borderRadius: 19 * vw,
    justifyContent: 'center',
    alignItems: 'center',
    transform: [
      {scaleX: 0.6},
      {scaleY: 0.6},
      {translateY: -5 * vh}
    ]
  },
  pointsScoreContainer: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
  },
  pointScoreValue: {
    fontSize: 7 * vw,
    color: 'white',
  },
  pointScoreTitle: {
    fontSize: 3.5 * vw,
    marginTop: -1 * vw,
    color: 'white',
    textAlign: 'center',
  },
  circularIndicatorBackground: {
    backgroundColor: '#7751bc',
    position: 'absolute',
    height: 33.33 * vw,
    width: 33.33 * vw,
    borderRadius: 16.66 * vw,
  },
  tickContainer: {
    backgroundColor: 'white',
    height: 5 * vw,
    width: 5 * vw,
    position: 'absolute',
    zIndex: 10,
    top: 31.915 * vw,
    borderRadius: 2.5 * vw,
    justifyContent: 'center',
    alignItems: 'center',
  },
  tickIcon: {
    height: 3.5 * vw,
    width: 3.5 * vw,
  },
  headerSectionTeacherName: {
    fontSize: 4 * vw,
    color: 'white',
    marginLeft: 6.66 * vw,
    marginTop: 1.5 * vh,
  },
  courseStats: {
    flexDirection: 'row',
    marginLeft: 6.66 * vw,
    alignItems: 'center',
    marginTop: vh,
  },
  courseStatText: {
    color: 'white',
    fontSize: 3 * vw,
  },
  courseStatImage: {
    height: 3 * vh,
    width: 3 * vh,
    marginRight: 2.5 * vw
  },
  chapterCard: {
    marginTop: 2 * vh,
    alignItems: 'center',
  },
  chapterSectionTitleSection: {
    flexDirection: 'row',
    width: 75 * vw,
    alignItems: 'center',
  },
  chapterSectionTitleIcon: {
    height: 3.5 * vw,
    width: 3.5 * vw,
    borderRadius: 2.5 * vw,
    marginRight: 2.5 * vw,
    borderWidth: 0.5 * vw,
    borderColor: '#5e4096'
  },
  chapterSectionTitleText: {
    fontSize: 4.5 * vw,
    color: 'black',
    fontFamily: 'Montserrat-SemiBold',
  },
  chapterCardContent: {
    backgroundColor: '#f6f6f6',
    width: 90 * vw,
    elevation: 5,
    borderRadius: 2 * vw,
    marginTop: 2.5 * vh,
    marginBottom: vh,
    overflow: 'hidden',
  },
  content: {
    paddingLeft: 16 * vw,
    justifyContent: 'center',
  },
  contentLine: {
    height: '100%',
    width: 2,
    backgroundColor: 'rgba(0,0,0,0.25)',
    position: 'absolute',
    left: 10 * vw - 0.5,
    opacity: 0.5,
  },
  contentIcon: {
    height: 5 * vw,
    width: 5 * vw,
    borderRadius: 2.5 * vw,
  },
  contentIconContainer: {
    position: 'absolute',
    left: 6.5 * vw,
    height: 7 * vw,
    width: 7 * vw,
    borderRadius: 3.5 * vw,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#f6f6f6',
  },
  contentName: {
    fontSize: 4.5 * vw,
    color: 'black',
    marginTop: 2 * vh,
    fontFamily: 'Montserrat-Medium'
  },
  contentDescriptionContainer: {
    flexDirection: 'row',
    width: 80 * vw,
    flex: 1,
  },
  contentDescription: {
    fontSize: 3.75 * vw,
    marginBottom: 2 * vh,
  },
  sectionCompleteDescriptionTickIcon: {
    height: 3.5 * vw,
    width: 3.5 * vw,
    marginTop: 1.25 * vw,
    marginLeft: vw,
  },
  progressLineIndicator: {
    width: vw,
    height: '100%',
    position: 'absolute',
    left: 0,
  },
  teacherProfileImageContainer: {
    height: 22 * vw,
    width: 22 * vw,
    borderRadius: 15 * vw,
    backgroundColor: 'black',
    position: 'absolute',
    top: 5 * vw,
    left: 39.25 * vw,
    overflow: 'hidden',
  },
  assignmentImageContainer: {
    height: 16 * vw,
    width: 16 * vw,
    borderRadius: 15 * vw,
    backgroundColor: 'black',
    position: 'absolute',
    top: 7 * vw,
    left: 13 * vw,
    overflow: 'hidden',
    alignItems: 'center',
  },
  videosImageContainer: {
    height: 16 * vw,
    width: 16 * vw,
    borderRadius: 15 * vw,
    backgroundColor: 'black',
    position: 'absolute',
    top: 7 * vw,
    right: 12.25 * vw,
    overflow: 'hidden',
    alignItems: 'center',
  },
  assignmentNumberText: {
    color: 'white',
    fontSize: 3.75 * vw,
    position: 'absolute',
    bottom: 2 * vw,
    fontWeight: 'bold',
  },
  teacherProfileImage: {
    height: '100%',
    width: '100%',
  },
  teacherInfoBox: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    top: 16 * vh,
  },
  teacherInfoName: {
    fontSize: 5 * vw,
    color: 'black',
    fontWeight: 'bold',
  },
  teacherInfoInstitute: {
    fontSize: 3.75 * vw,
    color: 'rgb(100,100,100)',
  },
  ratingContainer: {
    width: 100 * vw,
    height: 5.25 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  horizontalLine: {
    height: 0.25 * vh,
    backgroundColor: 'black',
    width: 100 * vw,
    position: 'absolute',
    opacity: 0.15,
  },
  rateNowButton: {
    width: 50 * vw,
    height: 5 * vh,
    marginBottom: 0.25 * vh,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 5,
  },
  overlayBg: {
    position: 'absolute',
    top: 0,
    left: 0,
    height: '100%',
    width: '100%',
  },
  rateNowText: {
    color: 'white',
    fontSize: 4.5 * vw,
    position: 'absolute',
    left: '40%',
  },
  ratingStars: {
    height: 6 * vw,
    width: 6 * vw,
  },
  ratingStarsContainer: {
    flexDirection: 'row',
    backgroundColor: '#f3f3f3',
    width: 50 * vw,
    justifyContent: 'space-around',
    alignItems: 'center',
    paddingLeft: 2 * vw,
    paddingRight: 2 * vw,
    height: 5 * vh,
    paddingBottom: 0.5 * vh,
    borderRadius: 2.5 * vh,
    elevation: 5,
  },
  continueLearningButtonContainer: {
    position: 'absolute',
    bottom: 0,
    elevation: 10,
    backgroundColor: 'white',
    width: 100 * vw,
    height: 12.5 * vh,
    justifyContent: 'center',
    alignItems: 'center',
  },
  continueLearningButton: {
    width: 80 * vw,
    height: 8 * vh,
    borderRadius: 4 * vh,
    justifyContent: 'center',
    backgroundColor: '#9e62db',
    alignItems: 'center',
  },
  continueLearningButtonText: {
    fontSize: 5 * vw,
    color: 'white',
  },
  pdf: {
    flex: 1,
    width: 100 * vw,
  },
  challengeModal: {
    height: 80 * vh,
    width: 90 * vw,
    borderRadius: 1.5 * vw,
    paddingTop: 4 * vh,
    paddingLeft: 7.5 * vw,
    paddingRight: 7.5 * vw,
    paddingBottom: 4 * vh,
    alignItems: 'center',
  },
  challengeTopSection: {
    height: 45 * vh,
    width: 80 * vw,
    borderRadius: 5 * vw,
    backgroundColor: 'white',
    elevation: 2,
    alignItems: 'center',
  },
  challengeTopSectionText: {
    fontSize: 5 * vw,
    fontFamily: 'Montserrat-SemiBold',
    marginTop: 2 * vh,
    marginBottom: 2 * vh,
    paddingLeft: 10 * vw,
    paddingRight: 10 * vw,
    color: 'black',
  },
  challengedIcon: {
    flex: 1,
    width: '75%',
    marginTop: 1 * vh,
  },
  snaptonextIcon: {
    position : 'absolute',
    height: '100%',
    width: '100%'
  },
  challengeButtonContainer: {
    flexDirection: 'row',
    overflow: 'hidden',
  },
  challengeModalButton: {
    flex: 1,
    height: 7 * vh,
    marginTop: 1 * vh,
    backgroundColor: '#a267cb',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomRightRadius: 5 * vw,
    borderBottomLeftRadius: 5 * vw,
    borderTopRightRadius: 5 * vw,
    borderTopLeftRadius: 5 * vw,
  },
 updateModalButton: {
    flex: 1,
    height: 7 * vh,
    marginTop: 2 * vh,
    width: 30 * vw,
    backgroundColor: '#025ef8',
    justifyContent: 'center',
    alignItems: 'center',
    borderBottomRightRadius: 5 * vw,
    borderBottomLeftRadius: 5 * vw,
    borderTopRightRadius: 5 * vw,
    borderTopLeftRadius: 5 * vw,
  },

  challengeModalButtonText: {
    fontSize: 5 * vw,
    fontFamily: 'Montserrat-Medium',
  },
  updateModalButtonText: {
    fontSize: 5 * vw,
    fontFamily: 'Montserrat-SemiBold',
    color: 'white'
  },
  teacherCardWrapper: {
    height: 35 * vh,
    width: 70 * vw,
    borderRadius: 5 * vw,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    marginTop: 3 * vh,
  },
  cardShadow:{
    height: 18 * vh,
    width: '100%',
    borderRadius: 5 * vw,
    elevation: 5,
    marginTop: 1 * vh,
    marginBottom: 1 * vh,
    marginLeft: 1.5 * vw,
    marginRight: 1.5 * vw,
  },
   cardcontentListShadow:{
    height: 30 * vh,
    width: '90%',
    borderRadius: 3 * vw,
    elevation: 5,
    marginTop: 1 * vh,
    marginBottom: 1 * vh,
    marginLeft: 5 * vw,
    marginRight: 1.5 * vw,
  },
  teacherImage: {
    height: 18 * vh,
    width: '97.5%',
    borderRadius: 2 * vw,
    resizeMode: 'cover',    
  },
   teachercontentListImage: {
    height: 14 * vh,
    width: 90 * vw, 
    resizeMode: 'cover', 
    borderRadius: 3 * vw,  
  },
   teachercontentListContainer: {
    height: 20 * vh,
    width: 90 * vw, 
    borderRadius: 5 * vw,
    marginTop: 1 * vh,
    marginBottom: 1 * vh,
    marginLeft: 1.5 * vw,
    marginRight: 1.5 * vw,  
    flex: 1,
    backgroundColor: '#012f47',
    flexDirection: 'row',
    elevation: 3,
  },
  chapterlistcard: {
    fontSize: 18,
    fontFamily: 'Montserrat-Bold',
    textAlign: 'left',
    color: 'white'

  },
  chapterlistcard1: {
    fontSize: 18,
    position: 'relative',
    fontFamily: 'Montserrat-Medium',
    textAlign: 'left',
    color: '#9BC9FF'

  },
  sharebox:{
    height : 10 * vh,
    width : 10 * vh,
    borderRadius: 5 * vh,
    backgroundColor : '#921bd0',
    elevation: 10,
    position: 'absolute',
    marginTop: 85 * vh ,
    marginRight : 15 * vw,
    alignItems:'center',
    justifyContent:'center',
    alignSelf: 'flex-end'

  },
  shareIcon: {
    resizeMode: 'contain',
    height: '60%',
    width: '60%',
    elevation: 3
  },

  ImageInChapterList: {
    width: '25%',
    height: '100%',
    resizeMode: 'contain',
    marginLeft: 2* vw,
    //marginLeft: 1 * vw,
  },
  ActivityIndicator: {
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40 * vh
  },
  dotImages: {
    width: '5%',
    height: '26%',
    marginLeft: 2 * vw,
    marginTop: 5.5 * vh,
    resizeMode: 'cover',
  },
  textBoxContainer: {
    marginTop: 1 * vh,
    marginBottom: 1 * vh,
    marginLeft: 1 * vw,
    marginRight: 1 * vw,
    marginLeft: 2 * vw,
    width: '60%',
    justifyContent: 'center',
  },
  description: {
    height: 15 * vh,
    width: 70 * vw,
    marginTop: 0.5 * vh,
    borderBottomLeftRadius: 5 * vw,
    borderBottomRightRadius: 5 * vw,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 2,
    borderColor: '#bcbcbc',
    backgroundColor: 'white',
    marginBottom: 0,
  },
  descriptionShadow: {
    height: 15 * vh,
    width: 70 * vw,
    borderRadius: 5 * vw,
    backgroundColor: '#bcbcbc',
  },
  teacherName: {
    fontSize: 16,
    color: 'black',
    marginTop: 0.5 * vh,
    marginLeft: 2 * vw,
  },
  coachingName: {
    fontSize: 15,
    color: 'white',
    opacity: 0.75,
  },
  linearGradient: {
    width: '90%',
    borderRadius: 3 * vw,
    marginTop: 1.5 * vh,
    marginBottom: 1.5 * vh,
    height: 18 * vh,
  },
  snapContainer: {
    marginTop: 1.5 * vh,
    width: 100 * vw,    
    backgroundColor: 'white',
    marginBottom: 2 * vw,
    height : 27 * vh,
    
 },
  snapcontentListContainer: {
    marginTop: 1.5 * vh,
    width: 100 * vw,    
    backgroundColor: 'white',
    marginBottom: 2 * vw,
    height : 160 * vh,
    
 },
 cardContainer: {
    width: 100 * vw,
    marginTop: 1.5 * vh,
    backgroundColor: '#00000000',
    marginBottom: 2 * vw,
 },
});

export default styles;